services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src/uploads:/app/src/uploads
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 